      - name: Собрать GeoIP для Proxy (заблокированные)
        run: |
          curl -s https://raw.githubusercontent.com/runetfreedom/russia-blocked-geoip/release/text/ru-blocked.txt > ip1.lst
          curl -s https://raw.githubusercontent.com/runetfreedom/russia-blocked-geoip/release/text/ru-blocked-community.txt > ip2.lst
          curl -s https://raw.githubusercontent.com/runetfreedom/russia-blocked-geoip/release/text/re-filter.txt > ip3.lst
          curl -s https://raw.githubusercontent.com/runetfreedom/russia-blocked-geoip/release/text/re.txt > ip4.lst
          curl -s https://raw.githubusercontent.com/runetfreedom/russia-blocked-geoip/release/text/ru-whitelist.txt > whitelist.lst

          cat ip1.lst ip2.lst ip3.lst ip4.lst custom/proxy-ips.txt 2>/dev/null | sort -u > raw-proxy-ips.txt
          # вычитаем whitelist - убираем из proxy-списка всё, что там перечислено как исключение
          grep -v -F -x -f whitelist.lst raw-proxy-ips.txt > all-proxy-ips.txt

          jq -R -s '{version:1, rules:[{ip_cidr: (split("\n") | map(select(length>0)))}]}' all-proxy-ips.txt > merged-proxy-ip.json

      - name: Собрать GeoIP для Bypass (вся РФ)
        run: |
          curl -s https://raw.githubusercontent.com/runetfreedom/russia-blocked-geoip/release/text/ru.txt > ru-all.lst
          cat ru-all.lst custom/bypass-ips.txt 2>/dev/null | sort -u > all-bypass-ips.txt
          jq -R -s '{version:1, rules:[{ip_cidr: (split("\n") | map(select(length>0)))}]}' all-bypass-ips.txt > merged-bypass-ip.json
